# http://snapcraft.io/docs/reference/
name: newsbeuter
version: '2.10'
icon: icon.png
summary: RSS feed reader for the text console
description: |
  Newsbeuter is an RSS feed reader for the text console.
  Zed Shaw called it "The Mutt of Feed Readers".

grade: devel        # stable devel
confinement: strict # strict devmode

apps:
  newsbeuter:
    command: env LOCPATH=$SNAP/usr/lib/locale newsbeuter
    plugs: [network]
  podbeuter:
    command: env LOCPATH=$SNAP/usr/lib/locale podbeuter
    plugs: [network]

parts:
  newsbeuter:
    plugin: make
    source: ../
    build-packages:
      - build-essential
      - libsqlite3-dev       # sqlite3
      - libcurl4-openssl-dev # libcurl
      - libxml2-dev          # libxml
      - libjson-c-dev        # json-c
      - libjson-glib-dev     # json
      - libncursesw5-dev     # ncursesw
      - libstfl-dev          # stfl
      - libssl-dev           # libcrypto
    organize:
      usr/local/bin/newsbeuter: bin/newsbeuter
      usr/local/bin/podbeuter: bin/podbeuter

    stage-packages:
      - locales-all          # without it gettext doesn't work #LP 1576282
    snap:
      - -usr/local/bin
      - -usr/local/share/doc
      - -usr/local/share/man
      - -usr/share

  desktopfile:
    plugin: dump
    source: misc
    organize:
      newsbeuter.desktop: meta/gui/newsbeuter.desktop
